import { units } from "$/helpers";

export const icons = {
	link: <i className="fa-solid fa-external-link" />,
	title: <i className="fa-solid fa-t" />,
	pack: <i className="fa-solid fa-folder-open" />,
	bpm: <img src="/images/metronome.png" style={{ width: units.rem(1) }} />,
	length: <i className="fa-solid fa-clock" />,
	released: <i className="fa-solid fa-calendar-days" />,
	characteristic: <i className="fa-solid fa-list" />,
	difficulty: <i className="fa-solid fa-star" />,
	nps: <img src="/images/nps.png" style={{ width: units.rem(1.25) }} />,
	colorNotes: <img src="/images/note.png" style={{ width: units.rem(1.25) }} />,
	bombNotes: <img src="/images/bomb.png" style={{ width: units.rem(1.25) }} />,
	obstacles: <img src="/images/obstacle.png" style={{ width: units.rem(1.25) }} />,
	sliders: <img src="/images/arc.png" style={{ width: units.rem(1) }} />,
	burstSliders: <i className="fa-solid fa-link" />,
	basicBeatmapEvents: <i className="fa-solid fa-cube" />,
	colorBoostBeatmapEvents: <i className="fa-solid fa-bolt" />,
	rotationEvents: <i className="fa-solid fa-compass" />,
	bpmEvents: <i className="fa-regular fa-clock" />,
	lightColorEventBoxGroups: <i className="fa-solid fa-lightbulb" />,
	lightRotationEventBoxGroups: <i className="fa-solid fa-rotate" />,
	lightTranslationEventBoxGroups: <i className="fa-solid fa-up-down-left-right" />,
	waypoints: <i className="fa-solid fa-location" />,
	basicEventTypesForKeyword: <i className="fa-solid fa-key" />,
	jumpSpeed: <i className="fa-solid fa-gauge" />,
	jumpOffset: <i className="fa-solid fa-left-right" />,
	hjd: <i className="fa-solid fa-timeline" />,
	jd: <i className="fa-solid fa-ruler" />,
	rt: <i className="fa-solid fa-stopwatch" />,
	mappers: <i className="fa-solid fa-user" />,
	lighters: <i className="fa-regular fa-user" />,
};
