name: Code Quality

on:
  push:
  workflow_dispatch:

env:
  NODE_VERSION: 20

jobs:
  check:
    name: Check (Biome)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
      - name: Run Biome
        run: biome ci .
  test:
    name: Run Unit Tests (Vitest)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn
      - name: Install dependencies
        run: yarn install --immutable
      - name: Prepare
        run: yarn prepare
      - name: Run Vitest
        run: yarn test run
